name: my_http
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_foreground_task: ^8.17.0
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  http: ^1.3.0
  mime: ^2.0.0
  network_info_plus: ^6.1.3
  path_provider: ^2.1.5
  permission_handler: ^11.4.0 
  synchronized: ^3.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/png/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: lib/assets/fonts/RobotoMono-Regular.ttf
  uses-material-design: true